/// AdMob / advertising configuration.
///
/// In a release build this file is generated by copying
/// `ad_secrets_example.dart` and replacing the placeholders with the real
/// Ad Unit IDs. The banner UI layer reads these constants, so the rest of the
/// codebase never has to know which (if any) ad provider is configured.
///
/// AdMob is **not** linked into this build, so [adsEnabled] is `false` and the
/// banner widget degrades to a zero-height, non-intrusive placeholder. When a
/// build that links `google_mobile_ads` is wired up, only this file and the
/// banner widget need to change.
abstract final class AdSecrets {
  /// Master switch for advertising. Always `false` in this dependency-free
  /// build so the game layout is never broken by an unavailable ad SDK.
  static const bool adsEnabled = false;

  /// Google-provided **test** banner ad units (safe to ship; real IDs replace
  /// these in production).
  static const String androidBannerAdUnitId =
      'ca-app-pub-3940256099942544/6300978111';
  static const String iosBannerAdUnitId =
      'ca-app-pub-3940256099942544/2934735716';

  /// App-level IDs required by the AdMob initializer.
  static const String androidAppId = 'ca-app-pub-3940256099942544~3347511713';
  static const String iosAppId = 'ca-app-pub-3940256099942544~1458002511';
}
